commit all my current changes

diff --git a/bash/bash_profile b/bash/bash_profile
--- a/bash/bash_profile
+++ b/bash/bash_profile
@@ -22,22 +22,23 @@ fi
 
 # Resolve DOTFILES_DIR (assuming ~/.dotfiles on distros without readlink and/or $BASH_SOURCE/$0)
 
-READLINK=$(which greadlink || which readlink)
-if $SHELL_BASH; then
-    CURRENT_SCRIPT=$BASH_SOURCE
-else
-    CURRENT_SCRIPT=$0
-fi
+# READLINK=$(which greadlink || which readlink)
+# if $SHELL_BASH; then
+#     CURRENT_SCRIPT=$BASH_SOURCE
+# else
+#     CURRENT_SCRIPT=$0
+# fi
 
-if [[ -n $CURRENT_SCRIPT && -x "$READLINK" ]]; then
-    SCRIPT_PATH=$($READLINK -f "$CURRENT_SCRIPT")
-    DOTFILES_DIR=$(dirname "$(dirname "$SCRIPT_PATH")")
-elif [ -d "$HOME/.dotfiles" ]; then
-    DOTFILES_DIR="$HOME/.dotfiles"
-else
-    echo "Unable to find dotfiles, exiting."
-    return # `exit 1` would quit the shell itself
-fi
+#if [[ -n $CURRENT_SCRIPT && -x "$READLINK" ]]; then
+#    SCRIPT_PATH=$($READLINK -f "$CURRENT_SCRIPT")
+#    DOTFILES_DIR=$(dirname "$(dirname "$SCRIPT_PATH")")
+# elif [ -d "$HOME/.dotfiles" ]; then
+#     DOTFILES_DIR="$HOME/.dotfiles"
+# else
+#     echo "Unable to find dotfiles, exiting."
+#     return # `exit 1` would quit the shell itself
+# fi
+DOTFILES_DIR="$HOME/.dotfiles"
 
 # Finally we can source the dotfiles (order matters)
 
@@ -88,6 +89,11 @@ fi
 
 # no autocomplete blank lines
 shopt -s no_empty_cmd_completion;
+
+# source bashrc
+if [ -f "$HOME/.bashrc" ]; then
+    source "$HOME/.bashrc"
+fi
 
 # Clean up
 
